---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dotbot.api.fullname" $ }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: {{ include "dotbot.api.fullname" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Namespace | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/part-of: {{ .Chart.Name | quote }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "dotbot.api.fullname" . }}
  template:
    metadata:
      {{- with .Values.api.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "dotbot.api.fullname" . }}
    spec:
      {{- if .Values.api.serviceAccount.create }}
      #serviceAccountName: {{ include "dotbot.api.fullname" $ }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      containers:
        - name: api
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
          image: {{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default $.Chart.AppVersion }}
          imagePullPolicy: {{ .Values.api.image.imagePullPolicy }}
          env:
          {{- with (concat .Values.global.env .Values.api.env) }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "dotbot.api.fullname" $ }}
            - secretRef:
                name: {{ (tpl .Values.api.existingSecret .) | default (include "dotbot.api.fullname" $) }}
          ports:
            - name: http
              containerPort: {{ .Values.api.containerPorts.http }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          {{- with .Values.api.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.api.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
